forms variables

'first_name',
'middle_name',
'last_name',
'gender',
'birth_date',
'age',
'place_birth',
'citizenship',
'religion',
'address',
'civil_status'
'email'

'first_choice',
'second_choice',
'school_year',
'semester',

'elementry_name',
'elementry_address',
'elementry_date',
'sr_high_name',
'sr_high_address',
'sr_high_date',
'last_school_name',
'last_school_address',
'last_school_date',
'graduated_from',
'date_graduation',
'average_grade',
'lrn',
'first_time_college',

'father_fullname',
'mother_fullname',
'guardian_fullname',
'father_date_birth',
'mother_date_birth',
'guardian_date_birth',
'father_education',
'mother_education',
'guardian_education',
'father_occupation',
'mother_occupation',
'guardian_occupation',
'father_company',
'mother_company',
'guardian_company',
'father_income',
'mother_income',
'guardian_income',
'father_contact',
'mother_contact',
'guardian_contact',
'signature'
